### ISSUE TITLE
Add simple clustering service

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-backend#48]
**Is your feature request related to a problem? Please describe.**
There is no existing service for the clustering.

**Describe the solution you'd like**
A service that computes the clustering using the existing pipeline.

**Comment by wittenator** [comment]
The server infrastructure exists, the the code from the notebook still needs to be transferred though

**Comment by ckinkeldey** [comment]
First step: without (with fixed) parameters

**Comment by jessebenjamin** [comment]
what's the status?

**Comment by jessebenjamin** [comment]
*bump*

**Comment by ckinkeldey** [comment]
Does not work for me and Lilli at the moment.

**Comment by ckinkeldey** [comment]
At the moment you return only the 9x9 clusters (workaround for trustvis). Please return all projects.

**Comment by wittenator** [comment]
Could you please describe what is not working using the Bug Report template in the repo? Otherwise I can't reproduce your problem

**Comment by ckinkeldey** [comment]
**Describe the bug**
rhyne:~ ck$ curl -X GET "https://localhost:5435/clustering" -k
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**To Reproduce**
curl in terminal

**Expected behavior**
return cluster.json

**Screenshots**
n/a

**Desktop (please complete the following information):**
- MacOS
- Ubuntu Linux

**Comment by wittenator** [comment]
The Topic Extraction service runs on http at the moment.
Therefore please use ```curl -X GET "http://localhost:5435/clustering" -k``` as a curl request.
