### ISSUE TITLE
Stash trained Doc2Vec model

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-backend#73]
Can we stash the trained doc2vec model in a file?

**Comment by wittenator** [comment]
Is there a technical reason for this? The model gets trained fast enough that it is not necessary to cache the model.

**Comment by jessebenjamin** [comment]
for us it takes a long time. how much time would it be on the server?

**Comment by wittenator** [comment]
What does a long time mean? Even if it takes 15 minutes, it only needs to be computed once at startup. Introducing a caching infrastructure for models was something I considered, but it would come at the cost of infrastructure complexity. Since the models would need to be persisted in the database, additional work on the DAL would be needed and you would have to add a signing procedure to decide if the underlying data and parameters for the model changed.

But running the whole dataset on my limb laptop takes 20 min max, so I assume that it can't be much longer on a way more powerful machine.

**Comment by jessebenjamin** [comment]
@polyphem @ckinkeldey ?

**Comment by jessebenjamin** [comment]
i guess the question was, when does the training happen, or the startup? so how does it happen in deployment...

**Comment by wittenator** [comment]
The training is done once on startup and effectively the model and the embedded documents are cached. That is also how the Jupyter Notebook works. You compute it once and for different queries from the viz you reuse the cached versions. I would copy this behaviour to the server version 1:1.

**Comment by jessebenjamin** [comment]
Agreed

**Comment by jessebenjamin** [comment]
though would -> will :)

**Comment by wittenator** [comment]
My hope was that somebody picks that up before I am back :D

**Comment by jessebenjamin** [comment]
There was too much else to do, we're strapped for human hours

**Comment by wittenator** [comment]
Understandably
