### ISSUE TITLE
Enrich project data with cooperation institutions

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-backend#9]
- [x] Get implicit link between projects and institutions from gepris via "Kooperationspartner"
- [x] coordinate with Tim on institution-endpoint

"Kooperationspartner" example:
http://gepris.dfg.de/gepris/projekt/283080919

**Comment by wittenator** [comment]
@polyphem Are you actually working on this?

Currently an unclean data set is a stopping this ticket, but once I have a cleaner one the extraction will be fast since the groundwork was already done.

**Comment by wittenator** [comment]
As mentioned the groundwork was done, which means a rework of the whole matching logic. Now the different files get loaded into a in-memory SQL database and connected via the corresponding SQL queries. This has the advantage that we can now put more or less unlimited files in there and don't write any real code which is specific to the file (which was necessary beforehands). Furthermore it is a bit faster and cleaner code-wise.

Furthermore they not only get cached, but also written to the disk in order to retrieve them on the next startup. If the files didn't change, no requests to the Google API are made.

**Comment by wittenator** [comment]
I implemented a rudimentary matching in SQL, but the names and addresses in both data sources differ. That makes a definite matching way harder. The matching product is not usable at the moment.

**Comment by wittenator** [comment]
@simon991 Since we don't have tests yet, could you run the application and look if everything suits your needs?
